// <auto-generated />
using System;
using MagicTown_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicTownAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230331182833_AgregarNumeroTownTabla")]
    partial class AgregarNumeroTownTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicTown_API.Modelos.NumeroTown", b =>
                {
                    b.Property<int>("TownNo")
                        .HasColumnType("int");

                    b.Property<string>("DetalleEspecial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("TownNo");

                    b.HasIndex("TownId");

                    b.ToTable("NumeroTowns");
                });

            modelBuilder.Entity("MagicTown_API.Modelos.Town", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "town detail...",
                            FechaActualizacion = new DateTime(2023, 3, 31, 15, 28, 33, 627, DateTimeKind.Local).AddTicks(3819),
                            FechaCreacion = new DateTime(2023, 3, 31, 15, 28, 33, 627, DateTimeKind.Local).AddTicks(3806),
                            ImagenURL = "",
                            MetrosCuadrados = 50,
                            Name = "Real Town",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "town detail...",
                            FechaActualizacion = new DateTime(2023, 3, 31, 15, 28, 33, 627, DateTimeKind.Local).AddTicks(3821),
                            FechaCreacion = new DateTime(2023, 3, 31, 15, 28, 33, 627, DateTimeKind.Local).AddTicks(3820),
                            ImagenURL = "",
                            MetrosCuadrados = 40,
                            Name = "Premium Town",
                            Ocupantes = 4,
                            Tarifa = 150.0
                        });
                });

            modelBuilder.Entity("MagicTown_API.Modelos.NumeroTown", b =>
                {
                    b.HasOne("MagicTown_API.Modelos.Town", "Town")
                        .WithMany()
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Town");
                });
#pragma warning restore 612, 618
        }
    }
}
